INSERT INTO organization_type (id, name) VALUES (1, 'Technology');
INSERT INTO organization_type (id, name) VALUES (2, 'Art');
INSERT INTO organization_type (id, name) VALUES (3, 'Education');
INSERT INTO organization_type (id, name) VALUES (4, 'Healthcare');
INSERT INTO organization_type (id, name) VALUES (5, 'Finance');
INSERT INTO organization_type (id, name) VALUES (6, 'Manufacturing');
INSERT INTO organization_type (id, name) VALUES (7, 'Retail');
INSERT INTO organization_type (id, name) VALUES (8, 'Transportation');
INSERT INTO organization_type (id, name) VALUES (9, 'Hospitality');
INSERT INTO organization_type (id, name) VALUES (10, 'Construction');
INSERT INTO organization_type (id, name) VALUES (11, 'Real Estate');
INSERT INTO organization_type (id, name) VALUES (12, 'Telecommunications');
INSERT INTO organization_type (id, name) VALUES (13, 'Media');
INSERT INTO organization_type (id, name) VALUES (14, 'Energy');
INSERT INTO organization_type (id, name) VALUES (15, 'Non-Profit');
INSERT INTO organization_type (id, name) VALUES (16, 'Government');
INSERT INTO organization_type (id, name) VALUES (17, 'Agriculture');
INSERT INTO organization_type (id, name) VALUES (18, 'Automotive');
INSERT INTO organization_type (id, name) VALUES (19, 'Aerospace');
INSERT INTO organization_type (id, name) VALUES (20, 'Biotechnology');
INSERT INTO organization_type (id, name) VALUES (21, 'Chemicals');
INSERT INTO organization_type (id, name) VALUES (22, 'Consulting');
INSERT INTO organization_type (id, name) VALUES (23, 'Consumer Goods');
INSERT INTO organization_type (id, name) VALUES (24, 'Defense');
INSERT INTO organization_type (id, name) VALUES (25, 'E-commerce');
INSERT INTO organization_type (id, name) VALUES (26, 'Entertainment');
INSERT INTO organization_type (id, name) VALUES (27, 'Environmental');
INSERT INTO organization_type (id, name) VALUES (28, 'Fashion');
INSERT INTO organization_type (id, name) VALUES (29, 'Food and Beverage');
INSERT INTO organization_type (id, name) VALUES (30, 'Gaming');
INSERT INTO organization_type (id, name) VALUES (31, 'Insurance');
INSERT INTO organization_type (id, name) VALUES (32, 'Legal');
INSERT INTO organization_type (id, name) VALUES (33, 'Logistics');
INSERT INTO organization_type (id, name) VALUES (34, 'Marketing');
INSERT INTO organization_type (id, name) VALUES (35, 'Mining');
INSERT INTO organization_type (id, name) VALUES (36, 'Music');
INSERT INTO organization_type (id, name) VALUES (37, 'Pharmaceuticals');
INSERT INTO organization_type (id, name) VALUES (38, 'Publishing');
INSERT INTO organization_type (id, name) VALUES (39, 'Research');
INSERT INTO organization_type (id, name) VALUES (40, 'Security');
INSERT INTO organization_type (id, name) VALUES (41, 'Sports');
INSERT INTO organization_type (id, name) VALUES (42, 'Tourism');
INSERT INTO organization_type (id, name) VALUES (43, 'Utilities');
INSERT INTO organization_type (id, name) VALUES (44, 'Venture Capital');
INSERT INTO organization_type (id, name) VALUES (45, 'Waste Management');
INSERT INTO organization_type (id, name) VALUES (46, 'Wholesale');
INSERT INTO organization_type (id, name) VALUES (47, 'Television');
INSERT INTO organization_type (id, name) VALUES (48, 'Radio');
INSERT INTO organization_type (id, name) VALUES (49, 'Advertising');
INSERT INTO organization_type (id, name) VALUES (50, 'Telecommunications');